#!/usr/bin/env python
# -*-coding: utf-8 -*-

DEPOSIT_TYPE_NORMAL = 0
DEPOSIT_TYPE_BUSINESS = 1
DEPOSIT_TYPE_PERSONAL_VIP = 2
DEPOSIT_TYPE_GOVERNMENT = 3
DEPOSIT_TYPE_BLACK_CARD = 4
DEPOSIT_TYPE_BANK_SPECIAL = 5

DEAL_TYPE_PAY = 0
DEAL_TYPE_COLLECTION = 1
