#! /usr/bin/env python
# -*- coding: utf-8 -*-
from models.young.new_user.user_follow_collect import FollowCollectObjType

check_config = [
    {
        "old_db": "user",
        "new_db": "passport",
        "old_table": "user",
        "new_table": "passport",
        "old_uks": ["passport_pid"],
        "new_uks": ["pid"],
        "old_2_new_column_map": {  # 新旧数据记录的字段对应。key是旧的表字段，value是新表对应字段，如果需要计算后再检查，value就是计算函数名（对应orm的property）
            "passport_pid": "pid",
            "phone": "phone",
            "passwd": "passwd",
            "salt": "salt",
            "last_login_time": "last_login_time",
            "status": "old_status",
            "create_time": "create_time",
        }
    },{
        "old_db": "user",
        "new_db": "passport",
        "old_table": "thirdparty_user",
        "new_table": "passport_thirdparty",
        "old_uks": ["snowflake_id"],
        "new_uks": ["id"],
        "old_2_new_column_map": {
            "snowflake_id": "id",
            "new_pid": "pid",
            "tp_type": "tp_type",
            "openid": "openid",
            "unionid": "unionid",
            "nickname": "nickname",
            "status": "status",
            "create_time": "create_time",
            "update_time": "update_time",
        }
    },{
        "old_db": "user",
        "new_db": "passport",
        "old_table": "thirdparty_binds",
        "new_table": "passport_thirdparty_bind",
        "old_uks": ["snowflake_id"],
        "new_uks": ["id"],
        "old_2_new_column_map": {
            "snowflake_id": "id",
            "new_bind_pid": "bind_pid",
            "bind_phone": "bind_phone",
            "tp_type": "tp_type",
            "openid": "openid",
            "status": "status",
            "create_time": "create_time",
            "update_time": "update_time",
        }
    },{
        "old_db": "user",
        "new_db": "new_user",
        "old_table": "medal",
        "new_table": "medal",
        "old_uks": ["id"],
        "new_uks": ["id"],
        "old_2_new_column_map": {
            "id": "id",
            "medal_type": "type",
            "l1_seq_no": "group_seq_no",
            "l2_seq_no": "item_seq_no",
            "l1_title": "l1_title",
            "l2_title": "l2_title",
            "l2_desc": "description",
            "l2_image_normal": "image_normal",
            "l2_image_gray": "image_gray",
            "l2_image_shadow": "image_shadow",
            "alter_image_url": "alter_image",
            "l2_obtain_num": "obtain_num",
            "unlock_time": "unlock_time",
            "status": "status",
            "create_time": "create_time",
            "update_time": "update_time",
        }
    },{
        "old_db": "user",
        "new_db": "new_user",
        "old_table": "user_medal",
        "new_table": "user_medal",
        "old_uks": ["id"],
        "new_uks": ["id"],
        "old_2_new_column_map": {
            "id": "id",
            "user_id": "user_id",
            "medal_id": "medal_id",
            "status": "status",
            "create_time": "create_time",
            "update_time": "update_time",
        }
    },{
        "old_db": "user",
        "new_db": "new_user",
        "old_table": "address_book",
        "new_table": "address_book",
        "old_uks": ["id"],
        "new_uks": ["id"],
        "old_2_new_column_map": {
            "id": "id",
            "user_id": "user_id",
            "name": "name",
            "phone": "phone",
            "district_id": "district_id",
            "address": "address",
            "status": "status",
            "create_time": "create_time",
            "update_time": "update_time",
        }
    },{
        "old_db": "course",
        "new_db": "new_user",
        "old_table": "interest_tag",
        "new_table": "interest_tag",
        "old_uks": ["id"],
        "new_uks": ["id"],
        "old_2_new_column_map": {
            "id": "id",
            "tag_name": "tag_name",
            "rank": "rank",
            "status": "status",
            "create_time": "create_time",
            "update_time": "update_time",
        }
    },{
        "old_db": "course",
        "new_db": "new_user",
        "old_table": "interest_user_tag",
        "new_table": "interest_user_tag",
        "old_uks": ["id"],
        "new_uks": ["id"],
        "old_2_new_column_map": {
            "id": "id",
            "user_id": "user_id",
            "tag_id": "tag_id",
            "status": "status",
            "create_time": "create_time",
            "update_time": "update_time",
        }
    },{
        "old_db": "user",
        "new_db": "new_user",
        "old_table": "user",
        "new_table": "profile",
        "old_uks": ["uid"],
        "new_uks": ["user_id"],
        "old_2_new_column_map": {
            "passport_pid": "pid",
            "uid": "user_id",
            "name": "name",
            "community_id": "community_id",
            "status": "old_status",
            "create_time": "create_time",
            "update_time": "update_time",
        }
    },{
        "old_db": "user",
        "new_db": "new_user",
        "old_table": "user_datum",
        "new_table": "profile_datum",
        "old_uks": ["user_id"],
        "new_uks": ["user_id"],
        "old_2_new_column_map": {
            "user_id": "user_id",
            "easemob_userid": "easemob_userid",
            "easemob_passwd": "easemob_passwd",
            "rongcloud_token": "rongcloud_token",
            "status": "status",
            "create_time": "create_time",
            "update_time": "update_time",
        }
    },{
        "old_db": "user",
        "new_db": "new_user",
        "old_table": "user_datum",
        "new_table": "profile",
        "old_uks": ["user_id"],
        "new_uks": ["user_id"],
        "old_2_new_column_map": {
            "user_id": "user_id",
            "sex": "sex",
            "new_birthday": "birthday",
            "weixin": "weixin",
            "email": "email",
            "bio": "signature",
            "bio_state": "signature_state",
            "industry": "industry",
            "industry_level_2": "industry_level_2",
            "work_time": "normal_work_time",
            "position": "position",
            "position_level": "position_level",
            "company": "company",
            "company_size": "company_size",
            "company_introduction": "company_introduction",
            "address": "company_address",
            "prov_name": "province",
            "city_name": "city",
            "district_name": "district",
            "status": "status",
            "create_time": "create_time",
            "update_time": "update_time",
        }
    },{
        "old_db": "user",
        "new_db": "new_user",
        "old_table": "user",
        "new_table": "profile_datum",
        "old_uks": ["uid"],
        "new_uks": ["user_id"],
        "old_2_new_column_map": {
            "uid": "user_id",
            "utype": "utype",
            "is_ever_super": "is_ever_super",
            "is_inner": "is_inner",
            "is_manual": "is_manual",
            "app_first_login_time": "app_first_login_time",
            "app_user_regist_time": "app_user_regist_time",
            "regist_channel": "regist_channel",
            "student_no": "student_no",
            "user_title_id": "user_title_id",
            "yxs_renew_price": "yxs_renew_price",
            "buyer_openid": "buyer_openid",
            "camp_skus": "camp_skus",
            "status": "old_status",
            "create_time": "create_time",
            "update_time": "update_time",
        }
    },{
        "old_db": "course",
        "new_db": "new_user",
        "old_table": "course_collect",
        "new_table": "user_follow_collect",
        "old_uks": ["user_id", "new_obj_type", "course_id"],
        "new_uks": ["user_id", "obj_type", "obj_id"],
        "new_special_filter_dict": {"obj_type": FollowCollectObjType.COURSE},
        "old_2_new_column_map": {
            "user_id": "user_id",
            "new_obj_type": "obj_type",
            "course_id": "obj_id",
            "source": "source",
            "state": "push_state",
        }
    },{
        "old_db": "course",
        "new_db": "new_user",
        "old_table": "practice_answer_collect",
        "new_table": "user_follow_collect",
        "old_uks": ["user_id", "new_obj_type", "answer_id"],
        "new_uks": ["user_id", "obj_type", "obj_id"],
        "new_special_filter_dict": {"obj_type": FollowCollectObjType.PRACTICE},
        "old_2_new_column_map": {
            "user_id": "user_id",
            "new_obj_type": "obj_type",
            "answer_id": "obj_id",
        }
    },{
        "old_db": "course",
        "new_db": "new_user",
        "old_table": "short_video_collect",
        "new_table": "user_follow_collect",
        "old_uks": ["user_id", "new_obj_type", "svideo_id"],
        "new_uks": ["user_id", "obj_type", "obj_id"],
        "new_special_filter_dict": {"obj_type": FollowCollectObjType.SHORT_VIDEO},
        "old_2_new_column_map": {
            "user_id": "user_id",
            "new_obj_type": "obj_type",
            "svideo_id": "obj_id",
        }
    },{
        "old_db": "user",
        "new_db": "new_user",
        "old_table": "follow_user",
        "new_table": "user_follow_collect",
        "old_uks": ["user_id", "new_obj_type", "dest_user_id"],
        "new_uks": ["user_id", "obj_type", "obj_id"],
        "new_special_filter_dict": {"obj_type": FollowCollectObjType.USER},
        "old_2_new_column_map": {
            "user_id": "user_id",
            "new_obj_type": "obj_type",
            "dest_user_id": "obj_id",
            "new_status": "status",
        }
    },{
        "old_db": "course",
        "new_db": "new_user",
        "old_table": "follow_topic",
        "new_table": "user_follow_collect",
        "old_uks": ["user_id", "new_obj_type", "topic_id"],
        "new_uks": ["user_id", "obj_type", "obj_id"],
        "new_special_filter_dict": {"obj_type": FollowCollectObjType.TOPIC},
        "old_2_new_column_map": {
            "user_id": "user_id",
            "new_obj_type": "obj_type",
            "topic_id": "obj_id",
            "new_status": "status",
        }
    }
]
